### Получение суммы зарплат сотрудников
GET http://localhost:8080/employee/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение всех сотрудников, зарплата которых больше средней
GET http://localhost:8080/employee/high-salary

### Добавление новых сотрудников
POST http://localhost:8080/employee
Content-Type: application/json

[
  {
    "name": "Максима",
    "salary": 89000,
    "position": "Мен"
  },
  {
    "name": "Эрик",
    "salary": 115000,
    "position": "ком"
  }
]

### Получение всех сотрудников
GET http://localhost:8080/employee/all

### Обновление сотрудника
PUT http://localhost:8080/employee/5
Content-Type: application/json

{
  "name": "Максим",
  "salary": 95000
}

### Получение сотрудника
GET http://localhost:8080/employee/2

### Удаление сотрудника
DELETE http://localhost:8080/employee/5

### Получение сотрудника с зп выше, чем
GET http://localhost:8080/employee/salaryHigherThan?salary=80000

### Получение сотрудника с макс ЗП
GET http://localhost:8080/employee/withHighestSalary

### Получение сотрудников
GET http://localhost:8080/employee?position=мен

### Получение полной информации о сотруднике
GET http://localhost:8080/employee/2/fullinfo

### Получение страницы сотрудников
GET http://localhost:8080/employee/page?page=0